version: '3.8'

networks:
    union-group:

volumes:
    union-group-database:
    union-group-storage:

services:
    nginx:
        image: nginx:stable-alpine
        container_name: nginx-union-group
        restart: unless-stopped
        ports:
            - "${NGINX_PORT}:80"
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./:/var/www/html:cached
        depends_on:
            - php
            - mysql
        networks:
            - union-group

    php:
        build:
            context: .
            dockerfile: docker/Dockerfile
        container_name: php-union-group
        restart: unless-stopped
        volumes:
            - ./:/var/www/html:cached
            - ./storage:/var/www/html/storage
        networks:
            - union-group
        environment:
            OPCACHE_MEMORY_CONSUMPTION: 128
            OPCACHE_MAX_ACCELERATED_FILES: 4000
            OPCACHE_VALIDATE_TIMESTAMPS: 1
            OPCACHE_REVALIDATE_FREQ: 2

    mysql:
        image: mysql:5.7.22
        container_name: mysql-union-group
        restart: unless-stopped
        tty: true
        volumes:
            - union-group-database:/var/lib/mysql
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - union-group

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin-union-group
        restart: unless-stopped
        depends_on:
            - mysql
        ports:
            - "${PM_PORT}:80"
        environment:
            PMA_HOST: ${DB_HOST}
            PMA_PORT: ${DB_PORT}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            PMA_ARBITRARY: 1
        networks:
            - union-group
